name: build

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Build Web
        working-directory: ./web
        run: |
          npm ci || npm i
          npm run build
      - uses: actions/setup-go@v5
        with:
          go-version: '1.21'
      - name: Build Backend
        run: go build ./cmd/netmanager
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Normalize repository (lowercase)
        id: repo
        run: |
          repo_lc=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
          echo "repo_lc=${repo_lc}" >> "$GITHUB_OUTPUT"
      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.ref == 'refs/heads/main' }}
          tags: ghcr.io/${{ steps.repo.outputs.repo_lc }}:latest
          build-args: |
            SZU_LOGIN_URL=https://github.com/Sleepstars/SZU-login/releases/latest/download/srun-login-linux-amd64

